name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.ipynb'
    branches:
      - master
  pull_request:
    branches: 
      - master

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        run: |
          docker-compose build test-navstack-gym
          docker-compose up -d
      - name: Test env
        run: docker-compose exec -T test-navstack-gym pytest
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.9
        with:
          python_version: "3.8.12"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
      - name: Slack Notification
        uses: homoluctus/slatify@master
        with:
          type: ${{ job.status }}
          job_name: '*[${{ env.PJ_REPO }}] Publish New Version*'
          channel: 'dev-rl-env'
          icon_emoji: ''
        env: 
          SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK }}